# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - master 
    - release/*
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://pandoc/latex:2.9.2.1
    
    steps:
    - uses: actions/checkout@v2

    - name: Create PDF
      run: | 
        pandoc --standalone --to pdf -o Ideas.pdf Ideas.md
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Ideas.pdf
        path: .
